/*
 * Copyright 2018 Jaroslav Groman
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package cz.jtek.popularmovies;

import android.content.Context;
import android.content.Intent;
import android.content.SharedPreferences;
import android.content.pm.PackageManager;
import android.support.v4.app.LoaderManager;
import android.support.v4.content.AsyncTaskLoader;
import android.support.v4.content.Loader;
import android.support.v7.app.AppCompatActivity;
import android.os.Bundle;
import android.support.v7.preference.PreferenceManager;
import android.support.v7.widget.GridLayoutManager;
import android.support.v7.widget.RecyclerView;
import android.util.Log;
import android.view.Menu;
import android.view.MenuInflater;
import android.view.MenuItem;
import android.view.View;
import android.widget.ProgressBar;
import android.widget.TextView;

import java.io.IOException;
import java.net.URL;

import cz.jtek.popularmovies.utilities.MockDataUtils;
import cz.jtek.popularmovies.utilities.NetworkUtils;
import cz.jtek.popularmovies.utilities.TmdbJsonUtils;

public class MainActivity
        extends AppCompatActivity
        implements MovieGridAdapter.MovieGridOnClickHandler,
        LoaderManager.LoaderCallbacks<TmdbData>,
        SharedPreferences.OnSharedPreferenceChangeListener {

    private static final String TAG = MainActivity.class.getSimpleName();

    private RecyclerView mRecyclerView;
    private TextView mErrorMessage;
    private ProgressBar mLoadingIndicator;

    private MovieGridAdapter mMovieGridAdapter;

    private static final int MOVIELIST_LOADER_ID = 0;

    // Bundle
    private static final String BUNDLE_KEY_PAGE = "page";
    private int mApiResultsPageToLoad = 1;

    private static boolean WERE_PREFERENCES_UPDATED = false;

    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.activity_main);

        mRecyclerView = findViewById(R.id.recyclerview_movies);
        mErrorMessage = findViewById(R.id.tv_error_message);
        mLoadingIndicator = findViewById(R.id.pb_loading);

        // Layout
        GridLayoutManager layoutManager = new GridLayoutManager(this, 3);
        mRecyclerView.setLayoutManager(layoutManager);

        mRecyclerView.setHasFixedSize(true);

        mMovieGridAdapter = new MovieGridAdapter(this);

        mRecyclerView.setAdapter(mMovieGridAdapter);

        // Loader
        LoaderManager.LoaderCallbacks<TmdbData> loaderCallbacks = MainActivity.this;

        Bundle loaderBundle = new Bundle();
        loaderBundle.putInt(BUNDLE_KEY_PAGE, mApiResultsPageToLoad);

        getSupportLoaderManager().initLoader(MOVIELIST_LOADER_ID, loaderBundle, loaderCallbacks);

        // Preference
        PreferenceManager.getDefaultSharedPreferences(this).registerOnSharedPreferenceChangeListener(this);


    }

    @Override
    public boolean onCreateOptionsMenu(Menu menu) {
        MenuInflater inflater = getMenuInflater();
        inflater.inflate(R.menu.menu_main, menu);
        return true;
    }

    @Override
    public boolean onOptionsItemSelected(MenuItem item) {
        int itemId = item.getItemId();

        if (R.id.action_settings == itemId) {
            Intent startSettingsActivity = new Intent(this, SettingsActivity.class);
            startActivity(startSettingsActivity);
            return true;
        }

        return super.onOptionsItemSelected(item);
    }

    @Override
    public void onClick(int itemId) {

    }

    @Override
    public Loader<TmdbData> onCreateLoader(int id, Bundle args) {
        mLoadingIndicator.setVisibility(View.VISIBLE);
        return new TmdbDataLoader(this, args);
    }

    /**
     * Called when a previously created loader has finished its load.
     *
     * @param loader   The Loader that has finished.
     * @param tmdbData The data generated by the Loader.
     */
    @Override
    public void onLoadFinished(Loader<TmdbData> loader, TmdbData tmdbData) {
        Log.d(TAG, "Load finished");
        mLoadingIndicator.setVisibility(View.INVISIBLE);
        mMovieGridAdapter.setMovieData(tmdbData);

        if (null == tmdbData) {
            showErrorMessage();
        } else {
            showMovieDataView();
        }
    }

    /**
     * Called when a previously created loader is being reset, and thus
     * making its data unavailable.  The application should at this point
     * remove any references it has to the Loader's data.
     *
     * @param loader The Loader that is being reset.
     */
    @Override
    public void onLoaderReset(Loader<TmdbData> loader) {
        // This method is not used but it is required to be overridden
    }

    /**
     * This method is used for resetting movie grid adapter contents.
     */
    private void invalidateData() {
        mMovieGridAdapter.setMovieData(null);
    }

    /**
     * This method will make the View for the movie data visible and
     * hide the error message.
     * <p>
     * Since it is okay to redundantly set the visibility of a View, we don't
     * need to check whether each view is currently visible or invisible.
     */
    private void showMovieDataView() {
        // Hide error message
        mErrorMessage.setVisibility(View.INVISIBLE);
        // Display movie grid
        mRecyclerView.setVisibility(View.VISIBLE);
    }

    /**
     * This method will make the error message visible and hide the weather
     * View.
     * <p>
     * Since it is okay to redundantly set the visibility of a View, we don't
     * need to check whether each view is currently visible or invisible.
     */
    private void showErrorMessage() {
        // Hide movie grid
        mRecyclerView.setVisibility(View.INVISIBLE);
        // Display error message
        mErrorMessage.setVisibility(View.VISIBLE);
    }

    @Override
    public void onSharedPreferenceChanged(SharedPreferences sharedPreferences, String s) {

    }

    @Override
    protected void onStart() {
        super.onStart();
    }



    public static class TmdbDataLoader extends AsyncTaskLoader<TmdbData> {

        final PackageManager mPackageManager;
        TmdbData mTmdbData = new TmdbData();
        Bundle mArgs;


        public TmdbDataLoader(Context context, Bundle args) {
            super(context);
            mPackageManager = getContext().getPackageManager();
            mArgs = args;
        }

        @Override
        protected void onStartLoading() {
            if (mTmdbData.getMovieList().size() != 0) {
                // If there are already data available, deliver them
                deliverResult(mTmdbData);
            } else {
                // Start background task
                forceLoad();
            }
        }

        /**
         * Handles a request to stop the Loader.
         */
        @Override
        protected void onStopLoading() {
            cancelLoad();
        }

        @Override
        public TmdbData loadInBackground() {

            // Get API results page to load from bundle
            int movieResultPage = mArgs.getInt(BUNDLE_KEY_PAGE, 1);

            Log.d(TAG, "Load in background, page: " + movieResultPage);

            try {
                // On loading first result page also load current API configuration
                if (movieResultPage == 1) {
                    // Load current API configuration
                    URL configUrl = NetworkUtils.buildConfigurationUrl();
                    //String jsonConfig = NetworkUtils.getResponseFromHttpUrl(configUrl);
                    String jsonConfig = MockDataUtils.getMockJson(getContext(), "mock_configuration");

                    TmdbJsonUtils.getConfigFromJson(mTmdbData, jsonConfig);
                    Log.d(TAG, mTmdbData.getConfig().getSecureBaseUrl());
                }

                // Load movie result page
                URL movieUrl = NetworkUtils.buildMovieUrl(getContext(), null, movieResultPage);
                //String jsonMovies = NetworkUtils.getResponseFromHttpUrl(movieUrl);
                String jsonMovies = MockDataUtils.getMockJson(getContext(), "mock_popular");

                TmdbJsonUtils.getMovieListFromJson(mTmdbData, jsonMovies);
                Log.d(TAG, mTmdbData.getMovieList().get(0).getTitle());

                return mTmdbData;

            } catch (IOException iex) {
                Log.e(TAG, "IOException ");
                iex.printStackTrace();
                return null;
            }
        }

    }
}
